FROM ubuntu:18.04
LABEL maintainer="H2o.ai <ops@h2o.ai>"

RUN apt-get update && \
    apt-get upgrade -y && \
    apt install -y unzip wget \
        build-essential cmake pkg-config checkinstall yasm \
        gfortran python3-dev python3 python3-pip \
        libjpeg-dev libpng-dev libtiff-dev libopenexr-dev libswscale-dev libatlas-base-dev libgtk-3-dev \
        tesseract-ocr libtesseract-dev && \
    apt auto-remove -y && \
    rm -rf /var/lib/apt/lists/*

ENV LC_ALL "C.UTF-8"
ENV LANG "C.UTF-8"
ENV PATH "${HOME}/.local/bin:${PATH}"